import type {
  Company,
  Client,
  Project,
  User,
  Invitation,
  ActivityItem,
  DashboardStats,
} from '@/types'

export const mockCompany: Company = {
  id: 'company-001',
  name: 'Rénovations Beaumont Inc.',
  email: 'info@renovationsbeaumont.ca',
  phone: '418-555-0192',
  address: '245 rue des Érables',
  city: 'Québec',
  province: 'QC',
  postal_code: 'G1K 3P4',
  logo_url: null,
  owner_id: 'user-001',
  subscription_plan: 'pro',
  license_number: 'RBQ-5632-8910',
  website: 'www.renovationsbeaumont.ca',
  created_at: '2024-03-15T10:00:00Z',
  updated_at: '2024-11-20T14:30:00Z',
}

export const mockUser: User = {
  id: 'user-001',
  email: 'marc.beaumont@renovationsbeaumont.ca',
  name: 'Marc Beaumont',
  role: 'company',
  company_id: 'company-001',
  avatar_url: null,
  created_at: '2024-03-15T10:00:00Z',
  updated_at: '2024-11-20T14:30:00Z',
}

export const mockClients: Client[] = [
  {
    id: 'client-001',
    company_id: 'company-001',
    name: 'Sophie Tremblay',
    email: 'sophie.tremblay@gmail.com',
    phone: '418-555-0347',
    address: '1842 boulevard Laurier',
    city: 'Sainte-Foy',
    province: 'QC',
    postal_code: 'G1V 2L3',
    notes: 'Propriétaire très engagée. Préfère les communications par courriel.',
    created_at: '2024-09-10T09:00:00Z',
    updated_at: '2024-11-15T16:00:00Z',
  },
  {
    id: 'client-002',
    company_id: 'company-001',
    name: 'Jean-François Côté',
    email: 'jfcote@hotmail.com',
    phone: '418-555-0589',
    address: '56 rue des Pins',
    city: 'Lévis',
    province: 'QC',
    postal_code: 'G6V 4R8',
    notes: 'Projet de remplacement de revêtement extérieur complet. Budget flexible.',
    created_at: '2024-10-02T11:30:00Z',
    updated_at: '2024-11-20T10:00:00Z',
  },
  {
    id: 'client-003',
    company_id: 'company-001',
    name: 'Marie-Claude Gagnon',
    email: 'mcgagnon@bell.net',
    phone: '418-555-0721',
    address: '318 avenue des Chênes',
    city: 'Charlesbourg',
    province: 'QC',
    postal_code: 'G2L 1N7',
    notes: 'Maison ancestrale construite en 1965. Travaux de rénovation majeurs planifiés.',
    created_at: '2024-11-01T14:00:00Z',
    updated_at: '2024-11-18T09:30:00Z',
  },
]

export const mockProjects: Project[] = [
  {
    id: 'project-001',
    company_id: 'company-001',
    client_id: 'client-001',
    client: mockClients[0],
    name: 'Rénovation extérieure - Tremblay',
    address: '1842 boulevard Laurier',
    city: 'Sainte-Foy',
    province: 'QC',
    postal_code: 'G1V 2L3',
    building_type: 'residential',
    status: 'report_ready',
    photos: [
      {
        id: 'photo-001',
        project_id: 'project-001',
        url: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
        angle: 'front',
        caption: 'Façade principale',
        order: 1,
        width: 1920,
        height: 1080,
        file_size: 2048000,
        created_at: '2024-10-15T14:00:00Z',
      },
      {
        id: 'photo-002',
        project_id: 'project-001',
        url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        angle: 'back',
        caption: 'Façade arrière',
        order: 2,
        width: 1920,
        height: 1080,
        file_size: 1850000,
        created_at: '2024-10-15T14:05:00Z',
      },
      {
        id: 'photo-003',
        project_id: 'project-001',
        url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
        angle: 'left_side',
        caption: 'Côté gauche',
        order: 3,
        width: 1920,
        height: 1080,
        file_size: 1720000,
        created_at: '2024-10-15T14:10:00Z',
      },
      {
        id: 'photo-004',
        project_id: 'project-001',
        url: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
        angle: 'right_side',
        caption: 'Côté droit',
        order: 4,
        width: 1920,
        height: 1080,
        file_size: 1680000,
        created_at: '2024-10-15T14:15:00Z',
      },
    ],
    measurements: {
      facade_width: 12.4,
      building_height: 7.2,
      wall_surface: 198.5,
      roof_surface: 145.2,
      window_count: 8,
      door_count: 2,
      perimeter: 42.6,
      confidence_level: 'high',
      notes: 'Mesures calculées avec haute précision à partir de 4 photos.',
    },
    materials: {
      wall_color: '#C8A882',
      roof_color: '#3D3D3D',
      trim_color: '#FFFFFF',
      door_color: '#8B4513',
      wall_material: 'vinyl',
      roof_material: 'shingle',
      accent_color: '#F97316',
    },
    notes: 'Remplacement complet du revêtement extérieur en vinyle. Le client souhaite une couleur beige chaleureux.',
    created_at: '2024-09-15T10:00:00Z',
    updated_at: '2024-11-10T16:30:00Z',
  },
  {
    id: 'project-002',
    company_id: 'company-001',
    client_id: 'client-002',
    client: mockClients[1],
    name: 'Revêtement Canexel - Côté',
    address: '56 rue des Pins',
    city: 'Lévis',
    province: 'QC',
    postal_code: 'G6V 4R8',
    building_type: 'residential',
    status: 'photos_received',
    photos: [
      {
        id: 'photo-005',
        project_id: 'project-002',
        url: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800',
        angle: 'front',
        caption: 'Façade avant',
        order: 1,
        width: 1920,
        height: 1080,
        file_size: 2100000,
        created_at: '2024-11-18T10:00:00Z',
      },
      {
        id: 'photo-006',
        project_id: 'project-002',
        url: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
        angle: 'front_left',
        caption: 'Coin avant gauche',
        order: 2,
        width: 1920,
        height: 1080,
        file_size: 1950000,
        created_at: '2024-11-18T10:05:00Z',
      },
    ],
    measurements: {
      facade_width: null,
      building_height: null,
      wall_surface: null,
      roof_surface: null,
      window_count: null,
      door_count: null,
      perimeter: null,
      confidence_level: null,
      notes: 'En attente d\'analyse.',
    },
    materials: {
      wall_color: null,
      roof_color: null,
      trim_color: null,
      door_color: null,
      wall_material: 'canexel',
      roof_material: 'shingle',
      accent_color: null,
    },
    notes: 'Le client veut du Canexel couleur Charcoal ou Driftwood. À confirmer.',
    created_at: '2024-11-05T09:00:00Z',
    updated_at: '2024-11-18T10:30:00Z',
  },
  {
    id: 'project-003',
    company_id: 'company-001',
    client_id: 'client-003',
    client: mockClients[2],
    name: 'Rénovation complète - Gagnon',
    address: '318 avenue des Chênes',
    city: 'Charlesbourg',
    province: 'QC',
    postal_code: 'G2L 1N7',
    building_type: 'residential',
    status: 'draft',
    photos: [],
    measurements: {
      facade_width: null,
      building_height: null,
      wall_surface: null,
      roof_surface: null,
      window_count: null,
      door_count: null,
      perimeter: null,
      confidence_level: null,
      notes: null,
    },
    materials: {
      wall_color: null,
      roof_color: null,
      trim_color: null,
      door_color: null,
      wall_material: null,
      roof_material: null,
      accent_color: null,
    },
    notes: 'Projet en phase initiale. Besoin d\'envoyer invitation pour photos.',
    created_at: '2024-11-20T14:00:00Z',
    updated_at: '2024-11-20T14:00:00Z',
  },
  {
    id: 'project-004',
    company_id: 'company-001',
    client_id: 'client-001',
    client: mockClients[0],
    name: 'Toiture - Tremblay (2e projet)',
    address: '1842 boulevard Laurier',
    city: 'Sainte-Foy',
    province: 'QC',
    postal_code: 'G1V 2L3',
    building_type: 'residential',
    status: 'invitation_sent',
    photos: [],
    measurements: {
      facade_width: null,
      building_height: null,
      wall_surface: null,
      roof_surface: null,
      window_count: null,
      door_count: null,
      perimeter: null,
      confidence_level: null,
      notes: null,
    },
    materials: {
      wall_color: null,
      roof_color: null,
      trim_color: null,
      door_color: null,
      wall_material: null,
      roof_material: 'metal',
      accent_color: null,
    },
    notes: 'Remplacement de la toiture existante par toiture métallique.',
    created_at: '2024-11-22T11:00:00Z',
    updated_at: '2024-11-22T11:30:00Z',
  },
]

export const mockInvitations: Invitation[] = [
  {
    id: 'inv-001',
    project_id: 'project-003',
    project: mockProjects[2],
    client_id: 'client-003',
    client: mockClients[2],
    token: 'tkn_abc123xyz789',
    expires_at: '2024-12-05T14:00:00Z',
    status: 'pending',
    message: 'Bonjour Marie-Claude, veuillez prendre quelques photos de votre maison selon les instructions ci-dessous.',
    created_at: '2024-11-20T14:05:00Z',
    updated_at: '2024-11-20T14:05:00Z',
  },
  {
    id: 'inv-002',
    project_id: 'project-004',
    project: mockProjects[3],
    client_id: 'client-001',
    client: mockClients[0],
    token: 'tkn_def456uvw012',
    expires_at: '2024-12-08T11:00:00Z',
    status: 'opened',
    message: 'Bonjour Sophie, pour votre projet de toiture, nous avons besoin de quelques photos.',
    created_at: '2024-11-22T11:30:00Z',
    updated_at: '2024-11-23T09:00:00Z',
  },
]

export const mockActivity: ActivityItem[] = [
  {
    id: 'act-001',
    company_id: 'company-001',
    type: 'photos_received',
    title: 'Photos reçues',
    description: 'Jean-François Côté a soumis 2 photos pour le projet "Revêtement Canexel - Côté"',
    project_id: 'project-002',
    client_id: 'client-002',
    created_at: '2024-11-18T10:30:00Z',
  },
  {
    id: 'act-002',
    company_id: 'company-001',
    type: 'invitation_sent',
    title: 'Invitation envoyée',
    description: 'Invitation envoyée à Sophie Tremblay pour le projet "Toiture - Tremblay (2e projet)"',
    project_id: 'project-004',
    client_id: 'client-001',
    created_at: '2024-11-22T11:30:00Z',
  },
  {
    id: 'act-003',
    company_id: 'company-001',
    type: 'report_generated',
    title: 'Rapport généré',
    description: 'Rapport PDF généré pour le projet "Rénovation extérieure - Tremblay"',
    project_id: 'project-001',
    client_id: 'client-001',
    created_at: '2024-11-10T16:30:00Z',
  },
  {
    id: 'act-004',
    company_id: 'company-001',
    type: 'project_created',
    title: 'Nouveau projet',
    description: 'Projet "Rénovation complète - Gagnon" créé pour Marie-Claude Gagnon',
    project_id: 'project-003',
    client_id: 'client-003',
    created_at: '2024-11-20T14:00:00Z',
  },
  {
    id: 'act-005',
    company_id: 'company-001',
    type: 'client_added',
    title: 'Nouveau client',
    description: 'Marie-Claude Gagnon ajoutée comme nouvelle cliente',
    project_id: null,
    client_id: 'client-003',
    created_at: '2024-11-01T14:00:00Z',
  },
]

export const mockDashboardStats: DashboardStats = {
  total_projects: 4,
  active_projects: 3,
  total_clients: 3,
  reports_generated: 1,
  photos_received: 6,
  invitations_sent: 2,
}

export function getProjectById(id: string): Project | undefined {
  return mockProjects.find((p) => p.id === id)
}

export function getClientById(id: string): Client | undefined {
  return mockClients.find((c) => c.id === id)
}

export function getInvitationByToken(token: string): Invitation | undefined {
  return mockInvitations.find((i) => i.token === token)
}

export function getProjectsByClientId(clientId: string): Project[] {
  return mockProjects.filter((p) => p.client_id === clientId)
}
